# -*- encoding: utf-8 -*-

=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.2.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "digital_femsa/version"

Gem::Specification.new do |s|
  s.name        = "digital_femsa"
  s.version     = DigitalFemsa::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DigitalFemsa"]
  s.email       = ["core@digitalfemsa.com"]
  s.homepage    = "https://www.digitalfemsa.com"
  s.summary     = "This library provides https://api.digitalfemsa.io operations"
  s.description = "Ruby library for https://api.digitalfemsa.io"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.6"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '= 2.14.2'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
