=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::BalancesApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
  end

  describe 'test an instance of BalancesApi' do
    it 'creates an instance of BalancesApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::BalancesApi)
    end
  end

  describe '#get_balance_with_http_info' do
    it 'raises for invalid accept_language' do
      expect do
        api_instance.get_balance_with_http_info(accept_language: 'fr')
      end.to raise_error(ArgumentError, /invalid value for "accept_language"/)
    end

    it 'sends GET request to balance endpoint' do
      expect(api_client).to receive(:call_api).with(:GET, '/balance', hash_including(
        operation: :'BalancesApi.get_balance',
        return_type: 'BalanceResponse'
      )).and_return([:balance, 200, {}])

      data = api_instance.get_balance(accept_language: 'es')
      expect(data).to eq(:balance)
    end
  end
end
