=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::ChargesApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of ChargesApi' do
    it 'creates an instance of ChargesApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::ChargesApi)
    end
  end

  describe '#get_charges_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_charges_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_charges_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps list filters into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/charges', hash_including(
        operation: :'ChargesApi.get_charges',
        query_params: {
          limit: 10,
          next: 'next_token',
          previous: 'prev_token',
          search: 'ord_123'
        },
        return_type: 'GetChargesResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_charges(
        limit: 10,
        _next: 'next_token',
        previous: 'prev_token',
        search: 'ord_123'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#orders_create_charge_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.orders_create_charge_with_http_info(nil, { amount: 1000 })
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'raises when charge_request is missing' do
      expect do
        api_instance.orders_create_charge_with_http_info('ord_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'charge_request'/)
    end

    it 'builds escaped path and sends charge payload' do
      payload = { amount: 1500, currency: 'MXN' }

      expect(api_client).to receive(:call_api).with(:POST, '/orders/ord%2F123/charges', hash_including(
        operation: :'ChargesApi.orders_create_charge',
        body: payload.to_json,
        return_type: 'ChargeOrderResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.orders_create_charge('ord/123', payload)
      expect(data).to eq(:created)
    end
  end

  describe '#update_charge_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.update_charge_with_http_info(nil, { reference_id: 'ref_1' })
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'raises when charge_update_request is missing' do
      expect do
        api_instance.update_charge_with_http_info('chg_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'charge_update_request'/)
    end

    it 'sends PUT request with serialized payload' do
      payload = { reference_id: 'new_reference' }

      expect(api_client).to receive(:call_api).with(:PUT, '/charges/chg_123', hash_including(
        operation: :'ChargesApi.update_charge',
        body: payload.to_json,
        return_type: 'ChargeResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_charge('chg_123', payload)
      expect(data).to eq(:updated)
    end
  end
end
