=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::CustomersApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of CustomersApi' do
    it 'creates an instance of CustomersApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::CustomersApi)
    end
  end

  describe '#create_customer_with_http_info' do
    it 'raises when customer is missing' do
      expect do
        api_instance.create_customer_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'customer'/)
    end

    it 'sends POST request with serialized customer body' do
      payload = { name: 'Vicente', email: 'vicente@example.com' }

      expect(api_client).to receive(:call_api).with(:POST, '/customers', hash_including(
        operation: :'CustomersApi.create_customer',
        body: payload.to_json,
        return_type: 'CustomerResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_customer(payload)
      expect(data).to eq(:created)
    end
  end

  describe '#create_customer_fiscal_entities_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.create_customer_fiscal_entities_with_http_info(nil, { rfc: 'XAXX010101000' })
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'raises when fiscal entity payload is missing' do
      expect do
        api_instance.create_customer_fiscal_entities_with_http_info('cus_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'customer_fiscal_entities_request'/)
    end

    it 'builds escaped path and sends POST request' do
      payload = { rfc: 'XAXX010101000' }

      expect(api_client).to receive(:call_api).with(:POST, '/customers/cus%2F123/fiscal_entities', hash_including(
        operation: :'CustomersApi.create_customer_fiscal_entities',
        body: payload.to_json,
        return_type: 'CreateCustomerFiscalEntitiesResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_customer_fiscal_entities('cus/123', payload)
      expect(data).to eq(:created)
    end
  end

  describe '#delete_customer_by_id_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.delete_customer_by_id_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends DELETE request to customer resource' do
      expect(api_client).to receive(:call_api).with(:DELETE, '/customers/cus_123', hash_including(
        operation: :'CustomersApi.delete_customer_by_id',
        return_type: 'CustomerResponse'
      )).and_return([:deleted, 200, {}])

      data = api_instance.delete_customer_by_id('cus_123')
      expect(data).to eq(:deleted)
    end
  end

  describe '#get_customers_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_customers_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_customers_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search filters to query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/customers', hash_including(
        operation: :'CustomersApi.get_customers',
        query_params: {
          limit: 20,
          search: 'vicente',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'CustomersResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_customers(
        limit: 20,
        search: 'vicente',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#update_customer_fiscal_entities_with_http_info' do
    it 'raises when fiscal_entities_id is missing' do
      expect do
        api_instance.update_customer_fiscal_entities_with_http_info('cus_123', nil, { business_name: 'Test SA' })
      end.to raise_error(ArgumentError, /Missing the required parameter 'fiscal_entities_id'/)
    end

    it 'sends PUT request with expected path and body' do
      payload = { business_name: 'Test SA' }

      expect(api_client).to receive(:call_api).with(:PUT, '/customers/cus_123/fiscal_entities/fis_123', hash_including(
        operation: :'CustomersApi.update_customer_fiscal_entities',
        body: payload.to_json,
        return_type: 'UpdateCustomerFiscalEntitiesResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_customer_fiscal_entities('cus_123', 'fis_123', payload)
      expect(data).to eq(:updated)
    end
  end
end
