=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::EventsApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
  end

  describe 'test an instance of EventsApi' do
    it 'creates an instance of EventsApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::EventsApi)
    end
  end

  describe '#get_event_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.get_event_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends GET request with escaped event path' do
      expect(api_client).to receive(:call_api).with(:GET, '/events/evt%2F123', hash_including(
        operation: :'EventsApi.get_event',
        return_type: 'EventResponse'
      )).and_return([:event, 200, {}])

      data = api_instance.get_event('evt/123')
      expect(data).to eq(:event)
    end
  end

  describe '#get_events_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_events_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_events_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/events', hash_including(
        operation: :'EventsApi.get_events',
        query_params: {
          limit: 30,
          search: 'charge.paid',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'GetEventsResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_events(
        limit: 30,
        search: 'charge.paid',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#resend_event_with_http_info' do
    it 'raises when webhook_log_id is missing' do
      expect do
        api_instance.resend_event_with_http_info('evt_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'webhook_log_id'/)
    end

    it 'sends POST request with escaped event and webhook log ids' do
      expect(api_client).to receive(:call_api).with(:POST, '/events/evt%2F123/webhook_logs/log%2F123/resend', hash_including(
        operation: :'EventsApi.resend_event',
        return_type: 'EventsResendResponse'
      )).and_return([:resent, 200, {}])

      data = api_instance.resend_event('evt/123', 'log/123')
      expect(data).to eq(:resent)
    end
  end
end
