=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::OrdersApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of OrdersApi' do
    it 'creates an instance of OrdersApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::OrdersApi)
    end
  end

  describe '#cancel_order_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.cancel_order_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'builds escaped path and sends POST request' do
      expect(api_client).to receive(:call_api).with(:POST, '/orders/order%2F123/cancel', hash_including(
        operation: :'OrdersApi.cancel_order',
        return_type: 'OrderResponse',
        auth_names: ['bearerAuth']
      )).and_return([:ok, 200, {}])

      data, status, _headers = api_instance.cancel_order_with_http_info('order/123')
      expect(data).to eq(:ok)
      expect(status).to eq(200)
    end
  end

  describe '#create_order_with_http_info' do
    it 'raises when order_request is missing' do
      expect do
        api_instance.create_order_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'order_request'/)
    end

    it 'sends serialized body and headers' do
      payload = { amount: 1000, currency: 'MXN' }

      expect(api_client).to receive(:call_api).with(:POST, '/orders', hash_including(
        operation: :'OrdersApi.create_order',
        body: payload.to_json,
        return_type: 'OrderResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_order(payload, accept_language: 'es', x_child_company_id: 'company_1')
      expect(data).to eq(:created)
    end
  end

  describe '#get_orders_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_orders_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_orders_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/orders', hash_including(
        operation: :'OrdersApi.get_orders',
        query_params: {
          limit: 10,
          search: 'john',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'GetOrdersResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_orders(
        limit: 10,
        search: 'john',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#order_cancel_refund_with_http_info' do
    it 'raises when refund_id is missing' do
      expect do
        api_instance.order_cancel_refund_with_http_info('ord_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'refund_id'/)
    end

    it 'sends DELETE request with expected path' do
      expect(api_client).to receive(:call_api).with(:DELETE, '/orders/ord_123/refunds/ref_123', hash_including(
        operation: :'OrdersApi.order_cancel_refund',
        return_type: 'OrderResponse'
      )).and_return([:deleted, 200, {}])

      data = api_instance.order_cancel_refund('ord_123', 'ref_123')
      expect(data).to eq(:deleted)
    end
  end

  describe '#order_refund_with_http_info' do
    it 'sends refund payload in POST body' do
      payload = { reason: 'requested_by_customer', amount: 500 }

      expect(api_client).to receive(:call_api).with(:POST, '/orders/ord_123/refunds', hash_including(
        operation: :'OrdersApi.order_refund',
        body: payload.to_json,
        return_type: 'OrderResponse'
      )).and_return([:refunded, 200, {}])

      data = api_instance.order_refund('ord_123', payload)
      expect(data).to eq(:refunded)
    end
  end

  describe '#orders_create_capture_with_http_info' do
    it 'sends capture payload in POST body' do
      payload = { amount: 300 }

      expect(api_client).to receive(:call_api).with(:POST, '/orders/ord_123/capture', hash_including(
        operation: :'OrdersApi.orders_create_capture',
        body: payload.to_json,
        return_type: 'OrderResponse'
      )).and_return([:captured, 200, {}])

      data = api_instance.orders_create_capture('ord_123', order_capture_request: payload)
      expect(data).to eq(:captured)
    end
  end

  describe '#update_order_with_http_info' do
    it 'raises when order_update_request is missing' do
      expect do
        api_instance.update_order_with_http_info('ord_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'order_update_request'/)
    end

    it 'sends PUT request with serialized body' do
      payload = { metadata: { source: 'tests' } }

      expect(api_client).to receive(:call_api).with(:PUT, '/orders/ord_123', hash_including(
        operation: :'OrdersApi.update_order',
        body: payload.to_json,
        return_type: 'OrderResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_order('ord_123', payload, accept_language: 'en')
      expect(data).to eq(:updated)
    end
  end
end
