=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::PaymentLinkApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of PaymentLinkApi' do
    it 'creates an instance of PaymentLinkApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::PaymentLinkApi)
    end
  end

  describe '#cancel_checkout_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.cancel_checkout_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends PUT request with escaped path' do
      expect(api_client).to receive(:call_api).with(:PUT, '/checkouts/cko%2F123/cancel', hash_including(
        operation: :'PaymentLinkApi.cancel_checkout',
        return_type: 'CheckoutResponse'
      )).and_return([:cancelled, 200, {}])

      data = api_instance.cancel_checkout('cko/123')
      expect(data).to eq(:cancelled)
    end
  end

  describe '#create_checkout_with_http_info' do
    it 'raises when checkout payload is missing' do
      expect do
        api_instance.create_checkout_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'checkout'/)
    end

    it 'sends POST request with serialized body' do
      payload = { name: 'Checkout Link', recurrent: false }

      expect(api_client).to receive(:call_api).with(:POST, '/checkouts', hash_including(
        operation: :'PaymentLinkApi.create_checkout',
        body: payload.to_json,
        return_type: 'CheckoutResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_checkout(payload)
      expect(data).to eq(:created)
    end
  end

  describe '#email_checkout_with_http_info' do
    it 'raises when email payload is missing' do
      expect do
        api_instance.email_checkout_with_http_info('cko_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'email_checkout_request'/)
    end

    it 'sends POST request to email endpoint' do
      payload = { email: 'buyer@example.com' }

      expect(api_client).to receive(:call_api).with(:POST, '/checkouts/cko_123/email', hash_including(
        operation: :'PaymentLinkApi.email_checkout',
        body: payload.to_json,
        return_type: 'CheckoutResponse'
      )).and_return([:sent, 200, {}])

      data = api_instance.email_checkout('cko_123', payload)
      expect(data).to eq(:sent)
    end
  end

  describe '#get_checkouts_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_checkouts_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_checkouts_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/checkouts', hash_including(
        operation: :'PaymentLinkApi.get_checkouts',
        query_params: {
          limit: 30,
          search: 'order_123',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'CheckoutsResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_checkouts(
        limit: 30,
        search: 'order_123',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end
end
