=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::PaymentMethodsApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'creates an instance of PaymentMethodsApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::PaymentMethodsApi)
    end
  end

  describe '#create_customer_payment_methods_with_http_info' do
    it 'raises when customer id is missing' do
      expect do
        api_instance.create_customer_payment_methods_with_http_info(nil, { type: 'oxxo' })
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'raises when payment method payload is missing' do
      expect do
        api_instance.create_customer_payment_methods_with_http_info('cus_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'create_customer_payment_methods_request'/)
    end

    it 'sends POST request with escaped customer path and serialized body' do
      payload = { type: 'card', token_id: 'tok_123' }

      expect(api_client).to receive(:call_api).with(:POST, '/customers/cus%2F123/payment_sources', hash_including(
        operation: :'PaymentMethodsApi.create_customer_payment_methods',
        body: payload.to_json,
        return_type: 'CreateCustomerPaymentMethodsResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_customer_payment_methods('cus/123', payload)
      expect(data).to eq(:created)
    end
  end

  describe '#delete_customer_payment_methods_with_http_info' do
    it 'raises when payment_method_id is missing' do
      expect do
        api_instance.delete_customer_payment_methods_with_http_info('cus_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'payment_method_id'/)
    end

    it 'sends DELETE request with escaped path components' do
      expect(api_client).to receive(:call_api).with(:DELETE, '/customers/cus%2F123/payment_sources/pm%2F123', hash_including(
        operation: :'PaymentMethodsApi.delete_customer_payment_methods',
        return_type: 'UpdateCustomerPaymentMethodsResponse'
      )).and_return([:deleted, 200, {}])

      data = api_instance.delete_customer_payment_methods('cus/123', 'pm/123')
      expect(data).to eq(:deleted)
    end
  end

  describe '#get_customer_payment_methods_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_customer_payment_methods_with_http_info('cus_123', limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_customer_payment_methods_with_http_info('cus_123', limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search filters to query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/customers/cus_123/payment_sources', hash_including(
        operation: :'PaymentMethodsApi.get_customer_payment_methods',
        query_params: {
          limit: 40,
          next: 'next_token',
          previous: 'prev_token',
          search: 'card'
        },
        return_type: 'GetPaymentMethodResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_customer_payment_methods(
        'cus_123',
        limit: 40,
        _next: 'next_token',
        previous: 'prev_token',
        search: 'card'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#update_customer_payment_methods_with_http_info' do
    it 'raises when update payload is missing' do
      expect do
        api_instance.update_customer_payment_methods_with_http_info('cus_123', 'pm_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'update_payment_methods'/)
    end

    it 'sends PUT request with serialized body' do
      payload = { expires_at: 1_700_000_000 }

      expect(api_client).to receive(:call_api).with(:PUT, '/customers/cus_123/payment_sources/pm_123', hash_including(
        operation: :'PaymentMethodsApi.update_customer_payment_methods',
        body: payload.to_json,
        return_type: 'UpdateCustomerPaymentMethodsResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_customer_payment_methods('cus_123', 'pm_123', payload)
      expect(data).to eq(:updated)
    end
  end
end
