=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::TransactionsApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
  end

  describe 'test an instance of TransactionsApi' do
    it 'creates an instance of TransactionsApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::TransactionsApi)
    end
  end

  describe '#get_transaction_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.get_transaction_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends GET request with escaped id path' do
      expect(api_client).to receive(:call_api).with(:GET, '/transactions/trx%2F123', hash_including(
        operation: :'TransactionsApi.get_transaction',
        return_type: 'TransactionResponse'
      )).and_return([:transaction, 200, {}])

      data = api_instance.get_transaction('trx/123')
      expect(data).to eq(:transaction)
    end
  end

  describe '#get_transactions_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_transactions_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_transactions_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps filters into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/transactions', hash_including(
        operation: :'TransactionsApi.get_transactions',
        query_params: {
          limit: 50,
          next: 'next_token',
          previous: 'prev_token',
          id: 'txn_filter',
          charge_id: 'chg_123',
          type: 'debit',
          currency: 'MXN'
        },
        return_type: 'GetTransactionsResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_transactions(
        limit: 50,
        _next: 'next_token',
        previous: 'prev_token',
        id: 'txn_filter',
        charge_id: 'chg_123',
        type: 'debit',
        currency: 'MXN'
      )

      expect(data).to eq(:list)
    end
  end
end
