=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::TransfersApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
  end

  describe 'test an instance of TransfersApi' do
    it 'creates an instance of TransfersApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::TransfersApi)
    end
  end

  describe '#get_transfer_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.get_transfer_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends GET request with escaped transfer id path' do
      expect(api_client).to receive(:call_api).with(:GET, '/transfers/trf%2F123', hash_including(
        operation: :'TransfersApi.get_transfer',
        return_type: 'TransferResponse'
      )).and_return([:transfer, 200, {}])

      data = api_instance.get_transfer('trf/123')
      expect(data).to eq(:transfer)
    end
  end

  describe '#get_transfers_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_transfers_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_transfers_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/transfers', hash_including(
        operation: :'TransfersApi.get_transfers',
        query_params: {
          limit: 20,
          search: 'bank',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'GetTransfersResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_transfers(
        limit: 20,
        search: 'bank',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end
end
