=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::WebhookKeysApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of WebhookKeysApi' do
    it 'creates an instance of WebhookKeysApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::WebhookKeysApi)
    end
  end

  describe '#create_webhook_key_with_http_info' do
    it 'sends POST request with serialized payload' do
      payload = { enabled: true }

      expect(api_client).to receive(:call_api).with(:POST, '/webhook_keys', hash_including(
        operation: :'WebhookKeysApi.create_webhook_key',
        body: payload.to_json,
        return_type: 'WebhookKeyCreateResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_webhook_key(webhook_key_request: payload)
      expect(data).to eq(:created)
    end
  end

  describe '#delete_webhook_key_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.delete_webhook_key_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends DELETE request with escaped id path' do
      expect(api_client).to receive(:call_api).with(:DELETE, '/webhook_keys/key%2F123', hash_including(
        operation: :'WebhookKeysApi.delete_webhook_key',
        return_type: 'WebhookKeyDeleteResponse'
      )).and_return([:deleted, 200, {}])

      data = api_instance.delete_webhook_key('key/123')
      expect(data).to eq(:deleted)
    end
  end

  describe '#get_webhook_keys_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_webhook_keys_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_webhook_keys_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps pagination and search query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/webhook_keys', hash_including(
        operation: :'WebhookKeysApi.get_webhook_keys',
        query_params: {
          limit: 50,
          search: 'active',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'GetWebhookKeysResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_webhook_keys(
        limit: 50,
        search: 'active',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#update_webhook_key_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.update_webhook_key_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends PUT request with serialized payload' do
      payload = { disabled: true }

      expect(api_client).to receive(:call_api).with(:PUT, '/webhook_keys/key_123', hash_including(
        operation: :'WebhookKeysApi.update_webhook_key',
        body: payload.to_json,
        return_type: 'WebhookKeyResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_webhook_key('key_123', webhook_key_update_request: payload)
      expect(data).to eq(:updated)
    end
  end
end
