=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

RSpec.describe DigitalFemsa::WebhooksApi do
  let(:config) { DigitalFemsa::Configuration.new }
  let(:api_client) { instance_double(DigitalFemsa::ApiClient) }
  let(:api_instance) { described_class.new(api_client) }

  before do
    allow(api_client).to receive(:config).and_return(config)
    allow(api_client).to receive(:select_header_accept).and_return('application/vnd.app-v2.1.0+json')
    allow(api_client).to receive(:select_header_content_type).and_return('application/json')
    allow(api_client).to receive(:object_to_http_body) { |value| value.to_json }
  end

  describe 'test an instance of WebhooksApi' do
    it 'creates an instance of WebhooksApi' do
      expect(api_instance).to be_instance_of(DigitalFemsa::WebhooksApi)
    end
  end

  describe '#create_webhook_with_http_info' do
    it 'raises when webhook_request is missing' do
      expect do
        api_instance.create_webhook_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'webhook_request'/)
    end

    it 'sends POST request with serialized payload' do
      payload = { url: 'https://example.com/hook', synchronous: false }

      expect(api_client).to receive(:call_api).with(:POST, '/webhooks', hash_including(
        operation: :'WebhooksApi.create_webhook',
        body: payload.to_json,
        return_type: 'WebhookResponse'
      )).and_return([:created, 201, {}])

      data = api_instance.create_webhook(payload)
      expect(data).to eq(:created)
    end
  end

  describe '#delete_webhook_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.delete_webhook_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends DELETE request with escaped id path' do
      expect(api_client).to receive(:call_api).with(:DELETE, '/webhooks/whk%2F123', hash_including(
        operation: :'WebhooksApi.delete_webhook',
        return_type: 'WebhookResponse'
      )).and_return([:deleted, 200, {}])

      data = api_instance.delete_webhook('whk/123')
      expect(data).to eq(:deleted)
    end
  end

  describe '#get_webhooks_with_http_info' do
    it 'raises for limit higher than 250' do
      expect do
        api_instance.get_webhooks_with_http_info(limit: 251)
      end.to raise_error(ArgumentError, /must be smaller than or equal to 250/)
    end

    it 'raises for limit lower than 1' do
      expect do
        api_instance.get_webhooks_with_http_info(limit: 0)
      end.to raise_error(ArgumentError, /must be greater than or equal to 1/)
    end

    it 'maps filters into query params' do
      expect(api_client).to receive(:call_api).with(:GET, '/webhooks', hash_including(
        operation: :'WebhooksApi.get_webhooks',
        query_params: {
          limit: 25,
          search: 'order',
          url: 'https://example.com/hook',
          next: 'next_token',
          previous: 'prev_token'
        },
        return_type: 'GetWebhooksResponse'
      )).and_return([:list, 200, {}])

      data = api_instance.get_webhooks(
        limit: 25,
        search: 'order',
        url: 'https://example.com/hook',
        _next: 'next_token',
        previous: 'prev_token'
      )

      expect(data).to eq(:list)
    end
  end

  describe '#test_webhook_with_http_info' do
    it 'raises when id is missing' do
      expect do
        api_instance.test_webhook_with_http_info(nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'id'/)
    end

    it 'sends POST request to test endpoint' do
      expect(api_client).to receive(:call_api).with(:POST, '/webhooks/whk_123/test', hash_including(
        operation: :'WebhooksApi.test_webhook',
        return_type: 'WebhookResponse'
      )).and_return([:tested, 200, {}])

      data = api_instance.test_webhook('whk_123')
      expect(data).to eq(:tested)
    end
  end

  describe '#update_webhook_with_http_info' do
    it 'raises when webhook_update_request is missing' do
      expect do
        api_instance.update_webhook_with_http_info('whk_123', nil)
      end.to raise_error(ArgumentError, /Missing the required parameter 'webhook_update_request'/)
    end

    it 'sends PUT request with serialized payload' do
      payload = { url: 'https://example.com/new-hook', disabled: false }

      expect(api_client).to receive(:call_api).with(:PUT, '/webhooks/whk_123', hash_including(
        operation: :'WebhooksApi.update_webhook',
        body: payload.to_json,
        return_type: 'WebhookResponse'
      )).and_return([:updated, 200, {}])

      data = api_instance.update_webhook('whk_123', payload)
      expect(data).to eq(:updated)
    end
  end
end
