=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module DigitalFemsa
  # Company balance summary.  Monetary fields are returned as arrays of amounts grouped by currency (see `balance_common_field` items). 
  class BalanceResponse
    # Amounts currently available, grouped by currency.
    attr_accessor :available

    # Amounts pending settlement, grouped by currency.
    attr_accessor :pending

    # Retention amount applied, grouped by currency.
    attr_accessor :retention_amount

    # Amounts currently retained, grouped by currency.
    attr_accessor :retained

    # Amounts temporarily retained, grouped by currency.
    attr_accessor :temporarily_retained

    # Target retention amount, grouped by currency.
    attr_accessor :target_retention_amount

    # Target temporary retention amount, grouped by currency.
    attr_accessor :target_temporary_retention_amount

    # Target collateral amount, grouped by currency.
    attr_accessor :target_collateral_amount

    # Gateway balance amounts, grouped by currency.
    attr_accessor :gateway

    # Cashout retention debited amounts, grouped by currency.
    attr_accessor :cashout_retention_debited

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'available' => :'available',
        :'pending' => :'pending',
        :'retention_amount' => :'retention_amount',
        :'retained' => :'retained',
        :'temporarily_retained' => :'temporarily_retained',
        :'target_retention_amount' => :'target_retention_amount',
        :'target_temporary_retention_amount' => :'target_temporary_retention_amount',
        :'target_collateral_amount' => :'target_collateral_amount',
        :'gateway' => :'gateway',
        :'cashout_retention_debited' => :'cashout_retention_debited'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'available' => :'Array<BalanceCommonField>',
        :'pending' => :'Array<BalanceCommonField>',
        :'retention_amount' => :'Array<BalanceCommonField>',
        :'retained' => :'Array<BalanceCommonField>',
        :'temporarily_retained' => :'Array<BalanceCommonField>',
        :'target_retention_amount' => :'Array<BalanceCommonField>',
        :'target_temporary_retention_amount' => :'Array<BalanceCommonField>',
        :'target_collateral_amount' => :'Array<BalanceCommonField>',
        :'gateway' => :'Array<BalanceCommonField>',
        :'cashout_retention_debited' => :'Array<BalanceCommonField>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalFemsa::BalanceResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalFemsa::BalanceResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'available')
        if (value = attributes[:'available']).is_a?(Array)
          self.available = value
        end
      else
        self.available = nil
      end

      if attributes.key?(:'pending')
        if (value = attributes[:'pending']).is_a?(Array)
          self.pending = value
        end
      else
        self.pending = nil
      end

      if attributes.key?(:'retention_amount')
        if (value = attributes[:'retention_amount']).is_a?(Array)
          self.retention_amount = value
        end
      else
        self.retention_amount = nil
      end

      if attributes.key?(:'retained')
        if (value = attributes[:'retained']).is_a?(Array)
          self.retained = value
        end
      else
        self.retained = nil
      end

      if attributes.key?(:'temporarily_retained')
        if (value = attributes[:'temporarily_retained']).is_a?(Array)
          self.temporarily_retained = value
        end
      else
        self.temporarily_retained = nil
      end

      if attributes.key?(:'target_retention_amount')
        if (value = attributes[:'target_retention_amount']).is_a?(Array)
          self.target_retention_amount = value
        end
      else
        self.target_retention_amount = nil
      end

      if attributes.key?(:'target_temporary_retention_amount')
        if (value = attributes[:'target_temporary_retention_amount']).is_a?(Array)
          self.target_temporary_retention_amount = value
        end
      else
        self.target_temporary_retention_amount = nil
      end

      if attributes.key?(:'target_collateral_amount')
        if (value = attributes[:'target_collateral_amount']).is_a?(Array)
          self.target_collateral_amount = value
        end
      else
        self.target_collateral_amount = nil
      end

      if attributes.key?(:'gateway')
        if (value = attributes[:'gateway']).is_a?(Array)
          self.gateway = value
        end
      else
        self.gateway = nil
      end

      if attributes.key?(:'cashout_retention_debited')
        if (value = attributes[:'cashout_retention_debited']).is_a?(Array)
          self.cashout_retention_debited = value
        end
      else
        self.cashout_retention_debited = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @available.nil?
        invalid_properties.push('invalid value for "available", available cannot be nil.')
      end

      if @pending.nil?
        invalid_properties.push('invalid value for "pending", pending cannot be nil.')
      end

      if @retention_amount.nil?
        invalid_properties.push('invalid value for "retention_amount", retention_amount cannot be nil.')
      end

      if @retained.nil?
        invalid_properties.push('invalid value for "retained", retained cannot be nil.')
      end

      if @temporarily_retained.nil?
        invalid_properties.push('invalid value for "temporarily_retained", temporarily_retained cannot be nil.')
      end

      if @target_retention_amount.nil?
        invalid_properties.push('invalid value for "target_retention_amount", target_retention_amount cannot be nil.')
      end

      if @target_temporary_retention_amount.nil?
        invalid_properties.push('invalid value for "target_temporary_retention_amount", target_temporary_retention_amount cannot be nil.')
      end

      if @target_collateral_amount.nil?
        invalid_properties.push('invalid value for "target_collateral_amount", target_collateral_amount cannot be nil.')
      end

      if @gateway.nil?
        invalid_properties.push('invalid value for "gateway", gateway cannot be nil.')
      end

      if @cashout_retention_debited.nil?
        invalid_properties.push('invalid value for "cashout_retention_debited", cashout_retention_debited cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @available.nil?
      return false if @pending.nil?
      return false if @retention_amount.nil?
      return false if @retained.nil?
      return false if @temporarily_retained.nil?
      return false if @target_retention_amount.nil?
      return false if @target_temporary_retention_amount.nil?
      return false if @target_collateral_amount.nil?
      return false if @gateway.nil?
      return false if @cashout_retention_debited.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          available == o.available &&
          pending == o.pending &&
          retention_amount == o.retention_amount &&
          retained == o.retained &&
          temporarily_retained == o.temporarily_retained &&
          target_retention_amount == o.target_retention_amount &&
          target_temporary_retention_amount == o.target_temporary_retention_amount &&
          target_collateral_amount == o.target_collateral_amount &&
          gateway == o.gateway &&
          cashout_retention_debited == o.cashout_retention_debited
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [available, pending, retention_amount, retained, temporarily_retained, target_retention_amount, target_temporary_retention_amount, target_collateral_amount, gateway, cashout_retention_debited].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalFemsa.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
