=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module DigitalFemsa
  # Order update payload. Only supported fields can be modified.
  class OrderUpdateRequest
    # Order status update. Allowed values depend on server-side validations.
    attr_accessor :status

    # Currency used for the order. Uses ISO 4217 (3-letter code). Allowed values depend on server-side validations.
    attr_accessor :currency

    attr_accessor :customer_info

    # List of products sold in the order.
    attr_accessor :line_items

    # List of shipping costs applied to the order.
    attr_accessor :shipping_lines

    attr_accessor :tax_lines

    # List of discounts applied to the order.
    attr_accessor :discount_lines

    # Additional information attached to the order.
    attr_accessor :metadata

    # URL to redirect the customer after completing the flow (when applicable).
    attr_accessor :return_url

    # Add new charges to the order. Subject to server-side validations (for example, maximum charges rules). 
    attr_accessor :charges

    # References an existing customer shipping contact.
    attr_accessor :shipping_contact_id

    attr_accessor :shipping_contact

    # References an existing customer fiscal entity.
    attr_accessor :fiscal_entity_id

    attr_accessor :fiscal_entity

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'status' => :'status',
        :'currency' => :'currency',
        :'customer_info' => :'customer_info',
        :'line_items' => :'line_items',
        :'shipping_lines' => :'shipping_lines',
        :'tax_lines' => :'tax_lines',
        :'discount_lines' => :'discount_lines',
        :'metadata' => :'metadata',
        :'return_url' => :'return_url',
        :'charges' => :'charges',
        :'shipping_contact_id' => :'shipping_contact_id',
        :'shipping_contact' => :'shipping_contact',
        :'fiscal_entity_id' => :'fiscal_entity_id',
        :'fiscal_entity' => :'fiscal_entity'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'status' => :'String',
        :'currency' => :'String',
        :'customer_info' => :'CustomerInfo',
        :'line_items' => :'Array<Product>',
        :'shipping_lines' => :'Array<ShippingRequest>',
        :'tax_lines' => :'Array<OrderTaxRequest>',
        :'discount_lines' => :'Array<OrderDiscountLinesRequest>',
        :'metadata' => :'Hash<String, Object>',
        :'return_url' => :'String',
        :'charges' => :'Array<ChargeRequest>',
        :'shipping_contact_id' => :'String',
        :'shipping_contact' => :'CustomerShippingContacts',
        :'fiscal_entity_id' => :'String',
        :'fiscal_entity' => :'OrderUpdateFiscalEntityRequest'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'shipping_contact_id',
        :'fiscal_entity_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalFemsa::OrderUpdateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalFemsa::OrderUpdateRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer_info')
        self.customer_info = attributes[:'customer_info']
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'shipping_lines')
        if (value = attributes[:'shipping_lines']).is_a?(Array)
          self.shipping_lines = value
        end
      end

      if attributes.key?(:'tax_lines')
        if (value = attributes[:'tax_lines']).is_a?(Array)
          self.tax_lines = value
        end
      end

      if attributes.key?(:'discount_lines')
        if (value = attributes[:'discount_lines']).is_a?(Array)
          self.discount_lines = value
        end
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      end

      if attributes.key?(:'charges')
        if (value = attributes[:'charges']).is_a?(Array)
          self.charges = value
        end
      end

      if attributes.key?(:'shipping_contact_id')
        self.shipping_contact_id = attributes[:'shipping_contact_id']
      end

      if attributes.key?(:'shipping_contact')
        self.shipping_contact = attributes[:'shipping_contact']
      end

      if attributes.key?(:'fiscal_entity_id')
        self.fiscal_entity_id = attributes[:'fiscal_entity_id']
      end

      if attributes.key?(:'fiscal_entity')
        self.fiscal_entity = attributes[:'fiscal_entity']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@currency.nil? && @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@currency.nil? && @currency.to_s.length > 3
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          status == o.status &&
          currency == o.currency &&
          customer_info == o.customer_info &&
          line_items == o.line_items &&
          shipping_lines == o.shipping_lines &&
          tax_lines == o.tax_lines &&
          discount_lines == o.discount_lines &&
          metadata == o.metadata &&
          return_url == o.return_url &&
          charges == o.charges &&
          shipping_contact_id == o.shipping_contact_id &&
          shipping_contact == o.shipping_contact &&
          fiscal_entity_id == o.fiscal_entity_id &&
          fiscal_entity == o.fiscal_entity
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [status, currency, customer_info, line_items, shipping_lines, tax_lines, discount_lines, metadata, return_url, charges, shipping_contact_id, shipping_contact, fiscal_entity_id, fiscal_entity].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalFemsa.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
