=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.2.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module DigitalFemsa
  # Order model. Some nested resources are returned as list previews (for example: `charges`, `line_items`), and may be `null` depending on the request/context. The `checkout` field is only present when the order is linked to a checkout (`channel.checkout_request_id`). 
  class OrderResponse
    attr_accessor :id

    attr_accessor :object

    attr_accessor :livemode

    attr_accessor :amount

    attr_accessor :currency

    # Current payment status of the order. It can be `null` for orders without payment information yet.
    attr_accessor :payment_status

    attr_accessor :amount_refunded

    # Indicates whether the order uses split payments (when available/configured).
    attr_accessor :split_payment

    # Metadata attached to the order.
    attr_accessor :metadata

    # Indicates whether the order is currently refundable.
    attr_accessor :is_refundable

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :customer_info

    attr_accessor :shipping_contact

    attr_accessor :channel

    attr_accessor :fiscal_entity

    attr_accessor :checkout

    attr_accessor :line_items

    attr_accessor :discount_lines

    attr_accessor :charges

    # Partial reference information (when applicable). Structure may vary depending on the payment flow.
    attr_accessor :partial_reference

    # Additional payment information (when available). Structure may vary.
    attr_accessor :payments_info

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object' => :'object',
        :'livemode' => :'livemode',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'payment_status' => :'payment_status',
        :'amount_refunded' => :'amount_refunded',
        :'split_payment' => :'split_payment',
        :'metadata' => :'metadata',
        :'is_refundable' => :'is_refundable',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'customer_info' => :'customer_info',
        :'shipping_contact' => :'shipping_contact',
        :'channel' => :'channel',
        :'fiscal_entity' => :'fiscal_entity',
        :'checkout' => :'checkout',
        :'line_items' => :'line_items',
        :'discount_lines' => :'discount_lines',
        :'charges' => :'charges',
        :'partial_reference' => :'partial_reference',
        :'payments_info' => :'payments_info'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'object' => :'String',
        :'livemode' => :'Boolean',
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'payment_status' => :'String',
        :'amount_refunded' => :'Integer',
        :'split_payment' => :'Boolean',
        :'metadata' => :'Hash<String, Object>',
        :'is_refundable' => :'Boolean',
        :'created_at' => :'Integer',
        :'updated_at' => :'Integer',
        :'customer_info' => :'OrderResponseCustomerInfo',
        :'shipping_contact' => :'OrderResponseShippingContact',
        :'channel' => :'OrderResponseChannel',
        :'fiscal_entity' => :'OrderFiscalEntityResponse',
        :'checkout' => :'OrderResponseCheckout',
        :'line_items' => :'OrderResponseProducts',
        :'discount_lines' => :'OrderResponseDiscountLines',
        :'charges' => :'OrderResponseCharges',
        :'partial_reference' => :'Hash<String, Object>',
        :'payments_info' => :'Hash<String, Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'payment_status',
        :'split_payment',
        :'shipping_contact',
        :'channel',
        :'fiscal_entity',
        :'partial_reference',
        :'payments_info'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalFemsa::OrderResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalFemsa::OrderResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      end

      if attributes.key?(:'livemode')
        self.livemode = attributes[:'livemode']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'payment_status')
        self.payment_status = attributes[:'payment_status']
      end

      if attributes.key?(:'amount_refunded')
        self.amount_refunded = attributes[:'amount_refunded']
      end

      if attributes.key?(:'split_payment')
        self.split_payment = attributes[:'split_payment']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'is_refundable')
        self.is_refundable = attributes[:'is_refundable']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'customer_info')
        self.customer_info = attributes[:'customer_info']
      end

      if attributes.key?(:'shipping_contact')
        self.shipping_contact = attributes[:'shipping_contact']
      end

      if attributes.key?(:'channel')
        self.channel = attributes[:'channel']
      end

      if attributes.key?(:'fiscal_entity')
        self.fiscal_entity = attributes[:'fiscal_entity']
      end

      if attributes.key?(:'checkout')
        self.checkout = attributes[:'checkout']
      end

      if attributes.key?(:'line_items')
        self.line_items = attributes[:'line_items']
      end

      if attributes.key?(:'discount_lines')
        self.discount_lines = attributes[:'discount_lines']
      end

      if attributes.key?(:'charges')
        self.charges = attributes[:'charges']
      end

      if attributes.key?(:'partial_reference')
        if (value = attributes[:'partial_reference']).is_a?(Hash)
          self.partial_reference = value
        end
      end

      if attributes.key?(:'payments_info')
        if (value = attributes[:'payments_info']).is_a?(Hash)
          self.payments_info = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@currency.nil? && @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      if !@metadata.nil? && @metadata.length > 100
        invalid_properties.push('invalid value for "metadata", number of items must be less than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      object_validator = EnumAttributeValidator.new('String', ["order"])
      return false unless object_validator.valid?(@object)
      return false if !@currency.nil? && @currency.to_s.length > 3
      return false if !@metadata.nil? && @metadata.length > 100
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('String', ["order"])
      unless validator.valid?(object)
        fail ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      if metadata.length > 100
        fail ArgumentError, 'invalid value for "metadata", number of items must be less than or equal to 100.'
      end

      @metadata = metadata
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object == o.object &&
          livemode == o.livemode &&
          amount == o.amount &&
          currency == o.currency &&
          payment_status == o.payment_status &&
          amount_refunded == o.amount_refunded &&
          split_payment == o.split_payment &&
          metadata == o.metadata &&
          is_refundable == o.is_refundable &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          customer_info == o.customer_info &&
          shipping_contact == o.shipping_contact &&
          channel == o.channel &&
          fiscal_entity == o.fiscal_entity &&
          checkout == o.checkout &&
          line_items == o.line_items &&
          discount_lines == o.discount_lines &&
          charges == o.charges &&
          partial_reference == o.partial_reference &&
          payments_info == o.payments_info
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object, livemode, amount, currency, payment_status, amount_refunded, split_payment, metadata, is_refundable, created_at, updated_at, customer_info, shipping_contact, channel, fiscal_entity, checkout, line_items, discount_lines, charges, partial_reference, payments_info].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalFemsa.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
