=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module DigitalFemsa
  # A transfer represents the action of sending an amount to a business bank account including the status, amount and destination used to make the transfer.
  class TransfersResponse
    # Unique identifier of the transfer.
    attr_accessor :id

    # Object name, which is transfer.
    attr_accessor :object

    # Amount in cents of the transfer.
    attr_accessor :amount

    # Date and time of creation of the transfer in Unix format.
    attr_accessor :created_at

    # The currency of the transfer. It uses the 3-letter code of ISO 4217.
    attr_accessor :currency

    # Indicates whether the transfer was created in live mode or test mode.
    attr_accessor :livemode

    # Code indicating transfer status.
    attr_accessor :status

    # Reference number of the transfer.
    attr_accessor :statement_reference

    # Description of the transfer.
    attr_accessor :statement_description

    attr_accessor :destination

    # Total fee for the transfer (present only when requesting the 'details' expansion).
    attr_accessor :fee

    # Present only when requesting the 'details' expansion.
    attr_accessor :capture_amount

    # Present only when requesting the 'details' expansion.
    attr_accessor :capture_fee

    # Present only when requesting the 'details' expansion.
    attr_accessor :capture_net

    # Present only when requesting the 'details' expansion.
    attr_accessor :refund_amount

    # Present only when requesting the 'details' expansion.
    attr_accessor :refund_fee

    # Present only when requesting the 'details' expansion.
    attr_accessor :refund_net

    # Present only when requesting the 'details' expansion.
    attr_accessor :payout_amount

    # Present only when requesting the 'details' expansion.
    attr_accessor :payout_fee

    # Present only when requesting the 'details' expansion.
    attr_accessor :payout_net

    # Present only when requesting the 'details' expansion.
    attr_accessor :transactions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object' => :'object',
        :'amount' => :'amount',
        :'created_at' => :'created_at',
        :'currency' => :'currency',
        :'livemode' => :'livemode',
        :'status' => :'status',
        :'statement_reference' => :'statement_reference',
        :'statement_description' => :'statement_description',
        :'destination' => :'destination',
        :'fee' => :'fee',
        :'capture_amount' => :'capture_amount',
        :'capture_fee' => :'capture_fee',
        :'capture_net' => :'capture_net',
        :'refund_amount' => :'refund_amount',
        :'refund_fee' => :'refund_fee',
        :'refund_net' => :'refund_net',
        :'payout_amount' => :'payout_amount',
        :'payout_fee' => :'payout_fee',
        :'payout_net' => :'payout_net',
        :'transactions' => :'transactions'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'object' => :'String',
        :'amount' => :'Integer',
        :'created_at' => :'Integer',
        :'currency' => :'String',
        :'livemode' => :'Boolean',
        :'status' => :'String',
        :'statement_reference' => :'String',
        :'statement_description' => :'String',
        :'destination' => :'TransfersResponseDestination',
        :'fee' => :'Integer',
        :'capture_amount' => :'Integer',
        :'capture_fee' => :'Integer',
        :'capture_net' => :'Integer',
        :'refund_amount' => :'Integer',
        :'refund_fee' => :'Integer',
        :'refund_net' => :'Integer',
        :'payout_amount' => :'Integer',
        :'payout_fee' => :'Integer',
        :'payout_net' => :'Integer',
        :'transactions' => :'Array<Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'fee',
        :'capture_amount',
        :'capture_fee',
        :'capture_net',
        :'refund_amount',
        :'refund_fee',
        :'refund_net',
        :'payout_amount',
        :'payout_fee',
        :'payout_net',
        :'transactions'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalFemsa::TransfersResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalFemsa::TransfersResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'livemode')
        self.livemode = attributes[:'livemode']
      else
        self.livemode = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'statement_reference')
        self.statement_reference = attributes[:'statement_reference']
      else
        self.statement_reference = nil
      end

      if attributes.key?(:'statement_description')
        self.statement_description = attributes[:'statement_description']
      else
        self.statement_description = nil
      end

      if attributes.key?(:'destination')
        self.destination = attributes[:'destination']
      else
        self.destination = nil
      end

      if attributes.key?(:'fee')
        self.fee = attributes[:'fee']
      end

      if attributes.key?(:'capture_amount')
        self.capture_amount = attributes[:'capture_amount']
      end

      if attributes.key?(:'capture_fee')
        self.capture_fee = attributes[:'capture_fee']
      end

      if attributes.key?(:'capture_net')
        self.capture_net = attributes[:'capture_net']
      end

      if attributes.key?(:'refund_amount')
        self.refund_amount = attributes[:'refund_amount']
      end

      if attributes.key?(:'refund_fee')
        self.refund_fee = attributes[:'refund_fee']
      end

      if attributes.key?(:'refund_net')
        self.refund_net = attributes[:'refund_net']
      end

      if attributes.key?(:'payout_amount')
        self.payout_amount = attributes[:'payout_amount']
      end

      if attributes.key?(:'payout_fee')
        self.payout_fee = attributes[:'payout_fee']
      end

      if attributes.key?(:'payout_net')
        self.payout_net = attributes[:'payout_net']
      end

      if attributes.key?(:'transactions')
        if (value = attributes[:'transactions']).is_a?(Array)
          self.transactions = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @object.nil?
        invalid_properties.push('invalid value for "object", object cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      if @livemode.nil?
        invalid_properties.push('invalid value for "livemode", livemode cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @statement_reference.nil?
        invalid_properties.push('invalid value for "statement_reference", statement_reference cannot be nil.')
      end

      if @statement_description.nil?
        invalid_properties.push('invalid value for "statement_description", statement_description cannot be nil.')
      end

      if @destination.nil?
        invalid_properties.push('invalid value for "destination", destination cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @object.nil?
      return false if @amount.nil?
      return false if @created_at.nil?
      return false if @currency.nil?
      return false if @currency.to_s.length > 3
      return false if @livemode.nil?
      return false if @status.nil?
      return false if @statement_reference.nil?
      return false if @statement_description.nil?
      return false if @destination.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object == o.object &&
          amount == o.amount &&
          created_at == o.created_at &&
          currency == o.currency &&
          livemode == o.livemode &&
          status == o.status &&
          statement_reference == o.statement_reference &&
          statement_description == o.statement_description &&
          destination == o.destination &&
          fee == o.fee &&
          capture_amount == o.capture_amount &&
          capture_fee == o.capture_fee &&
          capture_net == o.capture_net &&
          refund_amount == o.refund_amount &&
          refund_fee == o.refund_fee &&
          refund_net == o.refund_net &&
          payout_amount == o.payout_amount &&
          payout_fee == o.payout_fee &&
          payout_net == o.payout_net &&
          transactions == o.transactions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object, amount, created_at, currency, livemode, status, statement_reference, statement_description, destination, fee, capture_amount, capture_fee, capture_net, refund_amount, refund_fee, refund_net, payout_amount, payout_fee, payout_net, transactions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalFemsa.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
