=begin
#Femsa API

#Femsa sdk

The version of the OpenAPI document: 2.2.0
Contact: engineering@femsa.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'
require 'uri'

module DigitalFemsa
  # Parameters used to create or update a webhook.
  class WebhookRequest
    # Here you must place the URL of your Webhook remember that you must program what you will do with the events received. Also do not forget to handle the HTTPS protocol for greater security.
    attr_accessor :url

    # It is a value that allows to decide if the events will be synchronous or asynchronous. We recommend asynchronous = false
    attr_accessor :synchronous

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'url' => :'url',
        :'synchronous' => :'synchronous'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'url' => :'String',
        :'synchronous' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalFemsa::WebhookRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalFemsa::WebhookRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'synchronous')
        self.synchronous = attributes[:'synchronous']
      else
        self.synchronous = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      begin
        validate_url_safety(@url) if @url
      rescue ArgumentError => e
        invalid_properties.push(e.message)
      end

      if @synchronous.nil?
        invalid_properties.push('invalid value for "synchronous", synchronous cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @url.nil?
      begin
        validate_url_safety(@url)
      rescue ArgumentError
        return false
      end
      return false if @synchronous.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      validate_url_safety(url)
      @url = url
    end

    private

    # Comprehensive URL validation to prevent SSRF attacks
    # @param [String] url URL to validate
    def validate_url_safety(url)
      # Parse the URL to extract hostname
      begin
        uri = URI.parse(url)
        hostname = uri.hostname
        port = uri.port
        
        # Ensure URL has a valid scheme (http/https)
        unless uri.scheme =~ /\A(https?)\z/
          fail ArgumentError, "invalid value for \"url\", must use http or https scheme"
        end

        # Block if hostname is nil or empty
        if hostname.nil? || hostname.empty?
          fail ArgumentError, "invalid value for \"url\", hostname cannot be empty"
        end

        # Block localhost variations and private IP ranges
        if hostname_matches_restricted_patterns?(hostname)
          fail ArgumentError, "invalid value for \"url\", hostname points to restricted network resource"
        end

        # Block ports commonly used for internal services
        if port_matches_restricted_ports?(port)
          fail ArgumentError, "invalid value for \"url\", port is not allowed"
        end

      rescue URI::InvalidURIError
        fail ArgumentError, "invalid value for \"url\", must be a valid URL"
      end
    end

    # Check if hostname matches restricted patterns
    # @param [String] hostname Hostname to check
    # @return [Boolean] true if hostname is restricted
    def hostname_matches_restricted_patterns?(hostname)
      # Convert to lowercase for case-insensitive comparison
      hostname = hostname.downcase

      # Block localhost variations
      localhost_patterns = [
        'localhost',
        '127.0.0.1',
        '127.0.0.0',
        '0.0.0.0',
        '::1',
        '0:0:0:0:0:0:0:1',
        'ip6-localhost',
        'ip6-loopback'
      ]

      # Block private IP ranges
      private_ip_patterns = [
        /^127\.\d+\.\d+\.\d+/,      # 127.0.0.0/8 (loopback)
        /^10\.\d+\.\d+\.\d+/,       # 10.0.0.0/8
        /^172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+/,  # 172.16.0.0/12
        /^192\.168\.\d+\.\d+/,      # 192.168.0.0/16
        /^169\.254\.\d+\.\d+/,      # 169.254.0.0/16 (link-local)
        /^224\.\d+\.\d+\.\d+/,      # 224.0.0.0/4 (multicast)
        /^fc00:/,                    # fc00::/7 (IPv6 unique local)
        /^fe80:/,                    # fe80::/10 (IPv6 link-local)
        /^ff00:/                     # ff00::/8 (IPv6 multicast)
      ]

      # Block internal hostnames and services
      internal_hostnames = [
        'internal',
        'intranet',
        'corp',
        'private',
        'admin',
        'management',
        'api-gateway',
        'database',
        'cache',
        'redis',
        'mongo',
        'mysql',
        'postgres',
        'elasticsearch',
        'kibana',
        'grafana',
        'prometheus',
        'consul',
        'vault',
        'etcd',
        'zookeeper',
        'kafka',
        'rabbitmq'
      ]

      # Check localhost patterns
      return true if localhost_patterns.include?(hostname)

      # Check private IP ranges
      private_ip_patterns.each do |pattern|
        return true if hostname.match?(pattern)
      end

      # Check internal hostnames (including subdomains)
      internal_hostnames.each do |internal_name|
        return true if hostname.include?(internal_name)
      end

      # Check for common DNS rebinding services
      dns_rebinding_domains = [
        'xip.io',
        'nip.io',
        'sslip.io',
        'localtest.me',
        'vcap.me',
        'localho.st',
        '127-0-0-1.org.uk'
      ]

      dns_rebinding_domains.each do |domain|
        return true if hostname.end_with?(domain)
      end

      # Check if hostname resolves to private IP (basic check)
      # Note: In production, you might want to add actual DNS resolution here
      if hostname_resolves_to_private_ip?(hostname)
        return true
      end

      false
    end

    # Check if port matches restricted ports
    # @param [Integer] port Port to check
    # @return [Boolean] true if port is restricted
    def port_matches_restricted_ports?(port)
      return false if port.nil?  # Allow default ports

      # Block ports commonly used for internal services
      restricted_ports = [
        22,    # SSH
        23,    # Telnet
        25,    # SMTP
        53,    # DNS
        135,   # Windows RPC
        139,   # NetBIOS
        445,   # SMB
        1433,  # SQL Server
        1521,  # Oracle
        2049,  # NFS
        2181,  # Zookeeper
        3306,  # MySQL
        3389,  # RDP
        5432,  # PostgreSQL
        5672,  # RabbitMQ
        5984,  # CouchDB
        6379,  # Redis
        6380,  # Redis SSL
        8080,  # Common internal web services
        8081,  # Alternative web services
        8443,  # Alternative HTTPS
        9000,  # Common internal services
        9042,  # Cassandra
        9092,  # Kafka
        9200,  # Elasticsearch
        9300,  # Elasticsearch transport
        11211, # Memcached
        27017, # MongoDB
        27018, # MongoDB shard
        27019, # MongoDB config
        5000,  # Common internal services
        5001,  # Alternative services
        6000,  # Common internal services
        7000,  # Common internal services
        7001,  # WebLogic
        8000,  # Common internal services
        8001,  # Alternative services
        8009,  # AJP
        8443,  # Tomcat SSL
        8888,  # Common internal services
        9001,  # Common internal services
        9090,  # Common internal services
        9091,  # Common internal services
        9093,  # Common internal services
        9999,  # Common internal services
        10000, # Common internal services
        10001, # Common internal services
        10002, # Common internal services
        10003, # Common internal services
        10004, # Common internal services
        10005, # Common internal services
        10006, # Common internal services
        10007, # Common internal services
        10008, # Common internal services
        10009, # Common internal services
        10010  # Common internal services
      ]

      restricted_ports.include?(port)
    end

    # Basic check if hostname might resolve to private IP
    # @param [String] hostname Hostname to check
    # @return [Boolean] true if hostname might resolve to private IP
    def hostname_resolves_to_private_ip?(hostname)
      # This is a basic heuristic. In production, you might want to
      # actually resolve the hostname and check the IP addresses.
      
      # Check for common patterns that might resolve to internal IPs
      suspicious_patterns = [
        /^internal-/,
        /^private-/,
        /^intranet-/,
        /^corp-/,
        /^dev-/,
        /^test-/,
        /^staging-/,
        /^admin-/,
        /^db-/,
        /^cache-/,
        /^api-/,
        /^service-/,
        /^worker-/,
        /^node-/,
        /^server-/,
        /^host-/,
        /^vm-/,
        /^container-/
      ]

      suspicious_patterns.each do |pattern|
        return true if hostname.match?(pattern)
      end

      false
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          url == o.url &&
          synchronous == o.synchronous
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [url, synchronous].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalFemsa.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
